import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * RootLayout? 서버가 전체 앱에 반환하는 HTML을 한 번에 조작하는 방법
 * 서버 컴포넌트이며 페이지 이동 시 다시 렌더링 되지 않음
 * 즉, 레이아웃의 모든 데이터나 상태는 앱의 수명주기 내내 유지
 * @param param0
 * @returns
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
